### ISSUE TITLE
Confusion with the PaymentGateway testing situation with multiple sessions

### ISSUE THREAD

**Issue by guitarbien** [nothingworksinc/ticketbeast#28]
Is StripePaymentGatewayTest using newChargesDuring() to really correct ?

Testing in local machine runs perfectly, charge once, and the new charges count one, it's right. But I also use travis-ci to run 5.6, 7.0, 7.1 these three versions, and I got one version passed two versions failed ! Then I rebuild it each version it goes well. So I'm thinking that should we use the token to checkout the transaction result ? ( I've not check the stripe api yet, I think there should be this type of api )

Thanks.

**Comment by adamwathan** [comment]
I bet it's because it's running the test suite for all three PHP versions in parallel, so other processes are adding charges to the same Stripe test account at the same time.

This is one of those situations where you just have to deal with that limitation I think; Stripe is better than a lot of services in that at least we can run tests against it at all, but there's always going to be considerations you have to make to work within what the external service allows.

I don't think it's a huge deal in practice, but definitely an interesting limitation to be aware of!

**Comment by guitarbien** [comment]
Understood ! Thanks.
