### ISSUE TITLE
Timeframe

### ISSUE THREAD

**Issue by Hesesses** [nothingworksinc/ticketbeast#44]
> **When will the entire course be available?**
> 
> I really wanted to have the entire course ready before the holidays, but it’s turned out to be a bigger project than I planned!
> 
> I’m working full-time on the course until it’s finished, and I’m expecting all of the content to be available by the end of March 2017.

Is it realistic that the whole course would be available end of the March?

**Comment by adamwathan** [comment]
Hey @Hesesses! It's definitely taken more time and effort than I anticipated, and proven to be a lot of work trying to document the TDD process for an entire app from start to finish.

Realistically, the end of next month might still be a bit too ambitious, but I'm going to try my best to move faster (but never at the expense of quality.)

My hope is that now that we've covered a lot of the fundamental ideas and workflows that we can move faster through the rest of the features, skimming over anything similar to what's already been covered, and focusing the bulk of our time on just the ideas that are new, so hopefully the amount of content needed per new feature will continue to decrease.

My goal is to get the rest of the ticket ordering/customer side content released this week, and then next week we'll be into the admin/promoter side of the app.

Thanks for the question and hope that's a reasonable answer!

**Comment by Hesesses** [comment]
Sounds good!

**Comment by beerbuddha** [comment]
@adamwathan 
I like this small drip - I work full time and having a module here and there and THEN practice is a nice thing instead of blowing through the entire course in one shot. Even if you only release the entire thing in the summer, I am for one thankful for your course.

I'm already using your trait for API dumping the correct errors without the error handling code trapping it first.

Also being disciplined enough to record your mistakes, and actually writing this out completely rather than just skip forward shows a lot of thought process.

**Comment by curtisblackwell** [comment]
@adamwathan I definitely appreciate the times when you just show a completed test w/o walking through every step if there are no new concepts involved.

I usually hate video tutorials b/c of too much hand-holding and/or fluff. I love the way you do things, though. 😍
